### ISSUE TITLE
Out of Memory problem

### ISSUE THREAD

**Issue by Pertical** [sagieppel/Detecting-and-segmenting-and-classifying-materials-inside-vessels-in-images-using-convolutional-net#5]
Hi, thanks for sharing this great work, but I encountered a problem when I was trying to run your code. 

When I was trying to train this repository with LabPicsv1.2, I kept running into the situation that the training was "killed" and my computer is running out of memory (I have 32 GB ram on my desktop). It was the same situation with the other repository with the LabPicsV2 dataset. 

I tried to change a few parameters (MaxPixels, MaxBatchSize), but it didn't seem to solve the situation. I wonder how did you manage this issue while training this net.

Thanks, 
Peter

**Comment by sagieppel** [comment]
Its probably out of memory on the GPU  not on the computer RAM, what kind
of GPU do you have?

**Comment by Pertical** [comment]
Hi, thanks for the response. 

The model was running on an RTX3080ti, and I doubt it was the GPU memory's issue because the training was able to carry on to about 2400 iterations then the process got "killed". 

As I was monitoring the RAM usage, it kept increasing until it reached the maximum the got training stopped, so I am thinking it should be something going on with the dataloading process. I tried to change both MaxBatchSize to 1 and MaxPixels to 400*400*3 and the problem still exsits for me. 

Below is an example message I got from the terminal while training. 
### 
2410	 Semantic Loss 0.21532148733994572	 Ins Loss 2.5361129894357908	 Learning Rate 1e-05
Thermometer) 0.10208686495495731  Solid) 0.20193718101531946  PipeTubeStraw) 0.11082857281558722  VesselInsideVessel) 0.14722444307436774  Valve) 0.11014223978086612  SemiTrans) 0.16453044258164648  Powder) 0.09347240787760117  Granular) 0.13916879359819756  Foam) 0.1453543715101822  Gel) 0.15149364223589523  PropertiesMaterialInsideImmersed) 0.13283048884579501  Filled) 0.22984073476262715  Spike) 0.12491502567875222  Suspension) 0.127938254098813  Spatula) 0.10262157266627119  Cork) 0.10395907722497673  Opaque) 0.14794892389461595  Liquid) 0.20248119346619223  Filter) 0.10107598317175626  MaterialScattered) 0.12347620128155455  Transparent) 0.2942185654096528  MagneticStirer) 0.11371359094981945  Blood) 0.10902535532124327  Urine) 0.11763525869615282  Label) 0.10120632245475909  Part) 0.1254001493798522  Holder) 0.12654616376788583  Vapor) 0.1414714942369385  MaterialOnSurface) 0.06446530222160822  
2411
2412
Killed
###

Thanks, 
Peter

**Comment by sagieppel** [comment]
Sorry, I run the train.py from git for few hours and get no memory leak or
any error

**Comment by Pertical** [comment]
Thanks for the reply. 

I was able to conduct the training without any issues when I swicthed from Ubuntu22.04 to Win11. But I could not figure out the reason that caused the memory leak issue. 

Thanks, 
Peter

**Comment by sagieppel** [comment]
Glad to hear it!
I work with Ubuntu 22 so I doubt the operating system is the problem,
probably some installations.
